#Application Settings
#Sun May 19 05:09:28 CEST 2024
colorMode=false
imaginaryPart=0.45
juliaToggleSwitch=false
maxX=2.0
maxY=
minX=-2.0
minY=-2.0
realPart=-0.3
steps=775193.7984496115
transformation=Sierpinski
