#Application Settings
#Thu May 16 15:02:09 CEST 2024
colorMode=false
imaginaryPart=0.8
juliaToggleSwitch=false
maxX=4.0
maxY=10.0
minX=-4.0
minY=-1.0
realPart=-0.1
steps=3534883.7209302327
transformation=Mandelbrot
