#Application Settings
#Sat May 18 02:41:27 CEST 2024
colorMode=false
imaginaryPart=0.8
juliaToggleSwitch=false
maxX=2.0
maxY=2.0
minX=-2.0
minY=1.0
realPart=
steps=3720930.2325581396
transformation=Julia
